# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4896601528da19390d8e2e811aec9903c6259e3f51ccc8053bde60c3467c15dbc3ba585a681ada1141adcee3eb4468b0a2b80a61b1dae5bf654dc675e1fc6ad4

test:
  secret_key_base: fcdaa6c551deb7b811e9295573e1e81371f6ced84ad61f344e10728d4250dc157e3491b7f5b4c1f6eefa4da7020af5bb4db26a2a2e77d1fcc06f7bb7fb976732

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
